name: movie_browser
description: A Flutter application for browsing and viewing movie details.

environment:
  sdk: '>=3.5.0 <4.0.0'

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  http: ^1.2.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  flutter_intl: ^0.0.1
  build_runner: ^2.4.0
  json_serializable: ^6.6.2
  mockito: ^5.4.4

